#!/bin/bash

get_volume() {
    pamixer --get-volume
}

is_muted() {
    pamixer --get-mute
}

send_notification() {
    volume=$(get_volume)
    if [[ $(is_muted) == "true" ]]; then
        dunstify -a "volume-control" -u low -r 2593 -h int:value:0 "Volume muted" -t 2000
    else
        dunstify -a "volume-control" -u low -r 2593 -h int:value:"$volume" "Volume: ${volume}%" -t 2000
    fi
}

case $1 in
    up)
        pamixer -u
        pamixer -i 5 --allow-boost
        send_notification
        ;;
    down)
        pamixer -u
        pamixer -d 5
        send_notification
        ;;
    mute)
        pamixer -t
        send_notification
        ;;
    *)
        echo "Usage: $0 {up|down|mute}"
        exit 1
        ;;
esac 